@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Fuji",
  "email":"fuji@test2.com",
  "password":"123456"
}


###


# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"fuji@test2.com",
  "password":"123456"
}


###


# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title":"Nova pergunta 4",
  "content":"Conteúdo da pergunta 2"
}


###


# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}